### ISSUE TITLE
Radxa Zero 3w spec mismatch

### ISSUE THREAD

**Issue by halbGefressen** [OpenIPC/sbc-groundstations#10]
I read on the Radxa Datasheet that the HDMI out officially only supports up to 1080p60. Do people still get reliable 1080p120 output or are there issues?

**Comment by JohnDGodwin** [comment]
The zero 3w can output higher than 1080p60 yes.
If you are running the camera at 1080p120 you will need to run a low bitrate as the radxa cannot keep up with the decoding as well.
I can run an output at 1080p120 and run the camera at 720p120 and have no issues with 8Mbps.

**Comment by wildblue** [comment]
Which Hardware do you have? I saw, there are multiple different xonfigurations of the radix Board available.

**Comment by halbGefressen** [comment]
> Which Hardware do you have? I saw, there are multiple different xonfigurations of the radix Board available.

Currently none, I wanted to make sure I buy compatible hardware *before* complaining
