### ISSUE TITLE
A small suggestion about Radxa Zero 3

### ISSUE THREAD

**Issue by ningjx** [OpenIPC/sbc-groundstations#11]
A small suggestion, pins 27 and 28 on the Radxa Zero 3 can be used as USB pins to communicate with the network card. When designing buttons or other functions, could you avoid using these pins? Just like I2C, UART, or USB, etc.

**Comment by zhouruixi** [comment]
see my recommend
![GPIO功能分配-20241006](https://github.com/user-attachments/assets/876e3dc6-4cfc-491d-b260-c513f2a769f0)

**Comment by JohnDGodwin** [comment]
Future builds will move the recording button function. To be determined, probably to be compatible with RubyFPV.
