### ISSUE TITLE
Radaxa ROCK ZERO 3W version to buy.

### ISSUE THREAD

**Issue by azaslavskis** [OpenIPC/sbc-groundstations#16]
Hello, currently there is an many versions of radaxa 3W you can buy,
such as 
1. 1GB of RAM and 8GB EMMC
2. 2GB of RAM and 16GB EMMC
3. 4GB of RAM and 32GB EMMC
3. 8GB of RAM and 64GB EMMC

The quesiton is which one is minimum for run OpenIPC without issues? 
Many thanks. 
Alex

**Comment by JohnDGodwin** [comment]
It's been confirmed to run on as little as 1GB or RAM, and EMMC is optional.
