### ISSUE TITLE
resize.sh script does not work on emmc flash image

### ISSUE THREAD

**Issue by Ga1j1n** [OpenIPC/sbc-groundstations#9]
On a 2gb 16gb emmc model running script,resizefs.sh does nothing, I am unable to locate it in the scripts folder (might be worth detail commands to switch to this if rqd), In case this is because of the difference in model can you increase the models supported and maybe flesh the guidance out a little more for those of us at the pre-school level (Step by step command line prompts if possible )

**Comment by Ga1j1n** [comment]
If possible, could you document the pins to use for a 5v regulator / pwm fan / buttons (where supported)

**Comment by zhouruixi** [comment]
@Ga1j1n resizefs.sh is working on my radxa zero 3w with 2GB RAM + 16GB emmc

**Comment by JohnDGodwin** [comment]
resizefs.sh is no longer needed with the new images.
